### ISSUE TITLE
research the use of Swarm for primeCasino

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/solEVM-enforcer#135]
# Bounty
the design of the [SolEVM client app flow](https://docs.google.com/drawings/d/1WXcAvTEpXDGeL68MfWOP20mERht8rzqfSzdiFtYZeSc) requires a storage layer to to communicate CODE and DATA offchain between client and solvers/challengers. we found that IPFS uses protobuf and can not easily be proven on-chain.

## Scope
- read up on swarm
- whip up an on-chain proof algo

## Deliverables
- decision to use SWARM or not

## Gain for the project
- unblock Song of Dawn

## Roles
bounty gardener: @johannbarbie  / 10%
bounty worker: @pinkiebell  / 70%
bounty reviewer: @johannbarbie  / 20%

**Comment by johannbarbie** [comment]
for details see thread here: https://leapdao.slack.com/archives/CJCJRSEH4/p1560418154000400

**Comment by pinkiebell** [comment]
Result:
- wiki outdated
- lead me to https://github.com/ethersphere/swarm/blob/swarm-network-rewrite/swarm/storage/pyramid.go
- They call it `Pyramid Hash` / `Pyramid Chunker`

For us that means it will never ever go into our contracts due to complexity, gas costs and a general misfit for our architecture.
