### ISSUE TITLE
Keep track of the round updates in the Verifier contract

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/solEVM-enforcer#90]
# Bounty

Modify the Verifier contract to keep track of the merkle tree depth (solverExecutionLength).
It should not be possible to submit a proof before the path walking process reached the leaves.

Maybe change solverExecutionLength to solverExecutionDepth or something like that, 
so that we don't calculate the tree depth on-chain (gas cost).

Update tools/tests as necessary

## Deliverables
Security

## Gain for the project

Improve security for the on-chain verification game.

## Roles
bounty gardener: @pinkiebell  / 5%
bounty worker: name / share
bounty reviewer: name / share

**Comment by johannbarbie** [comment]
> Really? 😆

thinks about `alignment with purpose`, if not aligned with purpose, not a valid bounty.

**Comment by pinkiebell** [comment]
> > Really? 😆
> 
> thinks about `alignment with purpose`, if not aligned with purpose, not a valid bounty.

Better? 😎

**Comment by peara** [comment]
Currentl, `solverExecutionLength` is not yet used in the verification process yet. So as I understand, the problem is with case like this:
```
Solver: root = H(H(x), H(y))
Challenger: root = H(H(x), H(z))
```
So they can immediately use `submitProof` though we don't know if `x` is leaf or not.

For this case to work, we need to modify `submitProof` to be aware of tree depth and possibly add another function such as `negateDepthDif` which would required **solver** or **challenger** to submit a part of their merkle tree. The requirement is that after following this tree, we would have both at the same height and after that `respond` and `updateRound` can process correctly.

Am I correct :thinking:

**Comment by pinkiebell** [comment]
> @pinkiebell
> 
> Currently, `solverExecutionLength` is not yet used in the verification process yet. So as I understand, the problem is with case like this:
> 
> ```
> Solver: root = H(H(x), H(y))
> Challenger: root = H(H(x), H(z))
> ```
> So they can immediately use `submitProof` though we don't know if `x` is leaf or not.
> 
> For this case to work, we need to modify `submitProof` to be aware of tree depth and possibly add another function such as `negateDepthDif` which would required **solver** or **challenger** to submit a part of their merkle tree. The requirement is that after following this tree, we would have both at the same height and after that `respond` and `updateRound` can process correctly.
> 
> Am I correct 🤔

Yes. Basically rename & assume `solverExecutionLength` is `solverExecutionDepth` and decrement in every `updateRound`. `SubmitProof` should only work if they reached the leaves :)
